package com.example.myapplication.main.age_group.phonics.compare

import com.example.myapplication.main.base.nav.RouteNavigation
import com.example.myapplication.main.common.KidsFloatingShape
import com.example.myapplication.main.common.KidsGradient

// ComparisonData.kt
// "Compare & Choose" — head-to-head phonics comparisons (ai⚡ay, c⚡k⚡ck, …).
// Pure data — words whose audio is not recorded yet simply stay silent until added.
// Explanations use **markers** around the important words — the detail page
// renders them bold + tinted. Keep identical to iOS ComparisonData.swift.

// ── Models ───────────────────────────────────────────────────────────────────

data class ComparisonWord(
    val display: String,     // "rain" — highlight letters get tinted in team color
) {
    val audio: String get() = display
}

data class ComparisonTeam(
    val marker: String,      // shown on the answer button, e.g. "ai" or "/t/"
    val colorHex: Long,
    val zoneEmoji: String,   // 🏠 / 🏁 …
    val zoneHint: String,    // "middle" / "end" — tiny label next to the marker
    val markerAudio: String? = null, // blend sound file ("ai", "letter_c") — tap the zone header to hear it
    val highlight: String? = null,   // letters to tint inside words (defaults to marker)
) {
    val highlightText: String get() = highlight ?: marker
}

data class ComparisonQuizItem(
    val word: String,        // full word, e.g. "rain" (also the audio file)
    val blanked: String,     // "r__n" while unanswered (sound cards show the full word)
    val answerTeam: Int,     // index into teams
)

enum class ComparisonGroup {
    spelling,                // 📝 Which SPELLING? (same sound)
    sound,                   // 🔊 Which SOUND? (same spelling)
}

data class PhonicsComparison(
    val id: String,          // route key, e.g. "ai_ay"
    val cardTitle: String,   // "ai ⚡ ay" — grid card headline
    val shortTitle: String,  // "ai vs ay" — back button
    val rule: String,        // detective one-liner
    val explanation: String, // kid-friendly deeper "why" — **words** get highlighted
    val example: String,     // "rain · day" — grid card footer
    val group: ComparisonGroup,
    val linkedLevelNumber: Int,
    val linkedLevelLabel: String,   // "Level 13 · Vowel Teams"
    val linkedRoute: String,
    val gradient: KidsGradient,
    val shape: KidsFloatingShape,
    val teams: List<ComparisonTeam>,
    val quiz: List<ComparisonQuizItem>,
)

/**
 * One quiz round: a balanced random pick — every team gets its fair share of
 * the 8 questions (2 teams → 4+4, 3 teams → 3+3+2 with the lucky team random).
 */
fun makeComparisonQuizRound(comparison: PhonicsComparison, count: Int = 8): List<ComparisonQuizItem> {
    val teamsCount = comparison.teams.size
    if (teamsCount == 0) return emptyList()
    val byTeam = comparison.quiz.groupBy { it.answerTeam }
    val base = count / teamsCount
    val extra = count % teamsCount
    val luckyTeams = (0 until teamsCount).shuffled().take(extra).toSet()
    val round = mutableListOf<ComparisonQuizItem>()
    for (team in 0 until teamsCount) {
        val take = base + if (team in luckyTeams) 1 else 0
        round += (byTeam[team] ?: emptyList()).shuffled().take(take)
    }
    return round.shuffled()
}

// ── Catalog — 16 comparisons (newest words may await audio recordings; missing files are safely silent) ─────────────────────

val phonicsComparisons: List<PhonicsComparison> = listOf(

    PhonicsComparison(
        id = "ai_ay", cardTitle = "ai ⚡ ay", shortTitle = "ai vs ay",
        rule = "AI hides in the MIDDLE… AY loves being LAST!",
        explanation = "Both teams make the same long-A sound /ā/. The trick is WHERE the sound lives:\n• **Inside the word** → spell it **ai** (r-ai-n).\n• At the **end of a word** → English always picks **ay** (d-ay).",
        example = "rain · day", group = ComparisonGroup.spelling,
        linkedLevelNumber = 13, linkedLevelLabel = "Level 13 · Vowel Teams",
        linkedRoute = RouteNavigation.VowelTeamsIntro.route,
        gradient = KidsGradient.skyLavender, shape = KidsFloatingShape.sparkles,
        teams = listOf(
            ComparisonTeam("ai", 0xFF1565C0, "🏠", "middle", markerAudio = "ai"),
            ComparisonTeam("ay", 0xFFE65100, "🏁", "end", markerAudio = "ay"),
        ),
        quiz = listOf(
            ComparisonQuizItem("rain", "r__n", 0),
            ComparisonQuizItem("tail", "t__l", 0),
            ComparisonQuizItem("wait", "w__t", 0),
            ComparisonQuizItem("pain", "p__n", 0),
            ComparisonQuizItem("paint", "p__nt", 0),
            ComparisonQuizItem("mail", "m__l", 0),
            ComparisonQuizItem("chain", "ch__n", 0),
            ComparisonQuizItem("day", "d__", 1),
            ComparisonQuizItem("play", "pl__", 1),
            ComparisonQuizItem("stay", "st__", 1),
            ComparisonQuizItem("say", "s__", 1),
            ComparisonQuizItem("clay", "cl__", 1),
            ComparisonQuizItem("pray", "pr__", 1),
            ComparisonQuizItem("spray", "spr__", 1),
            ComparisonQuizItem("birthday", "birthd__", 1),
            ComparisonQuizItem("nail", "n__l", 0),
            ComparisonQuizItem("sail", "s__l", 0),
            ComparisonQuizItem("snail", "sn__l", 0),
            ComparisonQuizItem("train", "tr__n", 0),
            ComparisonQuizItem("brain", "br__n", 0),
            ComparisonQuizItem("grain", "gr__n", 0),
            ComparisonQuizItem("rail", "r__l", 0),
            ComparisonQuizItem("way", "w__", 1),
            ComparisonQuizItem("may", "m__", 1),
            ComparisonQuizItem("hay", "h__", 1),
            ComparisonQuizItem("tray", "tr__", 1),
            ComparisonQuizItem("gray", "gr__", 1),
            ComparisonQuizItem("away", "aw__", 1),
            ComparisonQuizItem("crayon", "cr__on", 1),
        ),
    ),

    PhonicsComparison(
        id = "oa_ow", cardTitle = "oa ⚡ ow", shortTitle = "oa vs ow",
        rule = "OA sits in the MIDDLE… OW takes the END!",
        explanation = "Both teams say the long-O sound /ō/.\n• **Inside a word** → usually **oa** (b-oa-t).\n• At the **end of a word** → almost always **ow** (sn-ow).",
        example = "boat · snow", group = ComparisonGroup.spelling,
        linkedLevelNumber = 13, linkedLevelLabel = "Level 13 · Vowel Teams",
        linkedRoute = RouteNavigation.VowelTeamsIntro.route,
        gradient = KidsGradient.oceanBlue, shape = KidsFloatingShape.waves,
        teams = listOf(
            ComparisonTeam("oa", 0xFF1565C0, "🏠", "middle", markerAudio = "oa"),
            ComparisonTeam("ow", 0xFF00897B, "🏁", "end", markerAudio = "ow"),
        ),
        quiz = listOf(
            ComparisonQuizItem("boat", "b__t", 0),
            ComparisonQuizItem("coat", "c__t", 0),
            ComparisonQuizItem("goat", "g__t", 0),
            ComparisonQuizItem("road", "r__d", 0),
            ComparisonQuizItem("toast", "t__st", 0),
            ComparisonQuizItem("throat", "thr__t", 0),
            ComparisonQuizItem("snow", "sn__", 1),
            ComparisonQuizItem("grow", "gr__", 1),
            ComparisonQuizItem("blow", "bl__", 1),
            ComparisonQuizItem("show", "sh__", 1),
            ComparisonQuizItem("slow", "sl__", 1),
            ComparisonQuizItem("glow", "gl__", 1),
            ComparisonQuizItem("flow", "fl__", 1),
            ComparisonQuizItem("soap", "s__p", 0),
            ComparisonQuizItem("load", "l__d", 0),
            ComparisonQuizItem("loaf", "l__f", 0),
            ComparisonQuizItem("goal", "g__l", 0),
            ComparisonQuizItem("foam", "f__m", 0),
            ComparisonQuizItem("coach", "c__ch", 0),
            ComparisonQuizItem("soak", "s__k", 0),
            ComparisonQuizItem("row", "r__", 1),
            ComparisonQuizItem("low", "l__", 1),
            ComparisonQuizItem("window", "wind__", 1),
            ComparisonQuizItem("yellow", "yell__", 1),
            ComparisonQuizItem("pillow", "pill__", 1),
            ComparisonQuizItem("rainbow", "rainb__", 1),
            ComparisonQuizItem("elbow", "elb__", 1),
        ),
    ),

    PhonicsComparison(
        id = "oi_oy", cardTitle = "oi ⚡ oy", shortTitle = "oi vs oy",
        rule = "OI stays in the MIDDLE… OY jumps to the END!",
        explanation = "Both teams make the /oy/ sound you hear in coin and boy.\n• **Inside the word** → write **oi** (c-oi-n).\n• At the **end of the word** → write **oy** (b-oy).",
        example = "coin · boy", group = ComparisonGroup.spelling,
        linkedLevelNumber = 14, linkedLevelLabel = "Level 14 · Diphthongs",
        linkedRoute = RouteNavigation.DiphthongsIntro.route,
        gradient = KidsGradient.peachYellow, shape = KidsFloatingShape.bubbles,
        teams = listOf(
            ComparisonTeam("oi", 0xFF7B1FA2, "🏠", "middle", markerAudio = "oi"),
            ComparisonTeam("oy", 0xFFE65100, "🏁", "end", markerAudio = "oy"),
        ),
        quiz = listOf(
            ComparisonQuizItem("coin", "c__n", 0),
            ComparisonQuizItem("soil", "s__l", 0),
            ComparisonQuizItem("join", "j__n", 0),
            ComparisonQuizItem("oil", "__l", 0),
            ComparisonQuizItem("coil", "c__l", 0),
            ComparisonQuizItem("foil", "f__l", 0),
            ComparisonQuizItem("boy", "b__", 1),
            ComparisonQuizItem("toy", "t__", 1),
            ComparisonQuizItem("joy", "j__", 1),
            ComparisonQuizItem("joyful", "j__ful", 1),
            ComparisonQuizItem("boil", "b__l", 0),
            ComparisonQuizItem("point", "p__nt", 0),
            ComparisonQuizItem("voice", "v__ce", 0),
            ComparisonQuizItem("noise", "n__se", 0),
            ComparisonQuizItem("moist", "m__st", 0),
            ComparisonQuizItem("joint", "j__nt", 0),
            ComparisonQuizItem("spoil", "sp__l", 0),
            ComparisonQuizItem("enjoy", "enj__", 1),
            ComparisonQuizItem("annoy", "ann__", 1),
            ComparisonQuizItem("destroy", "destr__", 1),
            ComparisonQuizItem("cowboy", "cowb__", 1),
        ),
    ),

    PhonicsComparison(
        id = "ou_ow", cardTitle = "ou ⚡ ow", shortTitle = "ou vs ow",
        rule = "OU works in the MIDDLE… OW finishes the word!",
        explanation = "Both teams shout the /ow!/ sound like when something surprises you.\n• **Inside a word** → usually **ou** (cl-ou-d).\n• At the **end** → it becomes **ow** (c-ow, h-ow).",
        example = "cloud · cow", group = ComparisonGroup.spelling,
        linkedLevelNumber = 14, linkedLevelLabel = "Level 14 · Diphthongs",
        linkedRoute = RouteNavigation.DiphthongsIntro.route,
        gradient = KidsGradient.creamMint, shape = KidsFloatingShape.dots,
        teams = listOf(
            ComparisonTeam("ou", 0xFF1565C0, "🏠", "middle", markerAudio = "ou"),
            ComparisonTeam("ow", 0xFFBF360C, "🏁", "end", markerAudio = "ow"),
        ),
        quiz = listOf(
            ComparisonQuizItem("cloud", "cl__d", 0),
            ComparisonQuizItem("loud", "l__d", 0),
            ComparisonQuizItem("found", "f__nd", 0),
            ComparisonQuizItem("out", "__t", 0),
            ComparisonQuizItem("count", "c__nt", 0),
            ComparisonQuizItem("mouth", "m__th", 0),
            ComparisonQuizItem("proud", "pr__d", 0),
            ComparisonQuizItem("cow", "c__", 1),
            ComparisonQuizItem("how", "h__", 1),
            ComparisonQuizItem("now", "n__", 1),
            ComparisonQuizItem("town", "t__n", 1),
            ComparisonQuizItem("down", "d__n", 1),
            ComparisonQuizItem("brown", "br__n", 1),
            ComparisonQuizItem("crown", "cr__n", 1),
            ComparisonQuizItem("clown", "cl__n", 1),
            ComparisonQuizItem("house", "h__se", 0),
            ComparisonQuizItem("mouse", "m__se", 0),
            ComparisonQuizItem("sound", "s__nd", 0),
            ComparisonQuizItem("round", "r__nd", 0),
            ComparisonQuizItem("shout", "sh__t", 0),
            ComparisonQuizItem("south", "s__th", 0),
            ComparisonQuizItem("ouch", "__ch", 0),
            ComparisonQuizItem("ground", "gr__nd", 0),
            ComparisonQuizItem("about", "ab__t", 0),
            ComparisonQuizItem("couch", "c__ch", 0),
            ComparisonQuizItem("owl", "__l", 1),
            ComparisonQuizItem("frown", "fr__n", 1),
            ComparisonQuizItem("gown", "g__n", 1),
            ComparisonQuizItem("wow", "w__", 1),
        ),
    ),

    PhonicsComparison(
        id = "au_aw", cardTitle = "au ⚡ aw", shortTitle = "au vs aw",
        rule = "AU likes the MIDDLE… AW likes the END!",
        explanation = "Both teams say /aw/ like in yawn.\n• In the **middle** of a word → write **au** (p-au-se).\n• At the **end** (or right before a final letter) → write **aw** (s-aw, dr-aw).",
        example = "pause · saw", group = ComparisonGroup.spelling,
        linkedLevelNumber = 14, linkedLevelLabel = "Level 14 · Diphthongs",
        linkedRoute = RouteNavigation.DiphthongsIntro.route,
        gradient = KidsGradient.pinkVanilla, shape = KidsFloatingShape.leaves,
        teams = listOf(
            ComparisonTeam("au", 0xFF6A1B9A, "🏠", "middle", markerAudio = "au"),
            ComparisonTeam("aw", 0xFFE65100, "🏁", "end", markerAudio = "aw"),
        ),
        quiz = listOf(
            ComparisonQuizItem("pause", "p__se", 0),
            ComparisonQuizItem("sauce", "s__ce", 0),
            ComparisonQuizItem("haul", "h__l", 0),
            ComparisonQuizItem("cause", "c__se", 0),
            ComparisonQuizItem("vault", "v__lt", 0),
            ComparisonQuizItem("because", "bec__se", 0),
            ComparisonQuizItem("saw", "s__", 1),
            ComparisonQuizItem("paw", "p__", 1),
            ComparisonQuizItem("draw", "dr__", 1),
            ComparisonQuizItem("straw", "str__", 1),
            ComparisonQuizItem("jaw", "j__", 1),
            ComparisonQuizItem("yawn", "y__n", 1),
            ComparisonQuizItem("autumn", "__tumn", 0),
            ComparisonQuizItem("launch", "l__nch", 0),
            ComparisonQuizItem("author", "__thor", 0),
            ComparisonQuizItem("august", "__gust", 0),
            ComparisonQuizItem("astronaut", "astron__t", 0),
            ComparisonQuizItem("laundry", "l__ndry", 0),
            ComparisonQuizItem("law", "l__", 1),
            ComparisonQuizItem("raw", "r__", 1),
            ComparisonQuizItem("claw", "cl__", 1),
            ComparisonQuizItem("dawn", "d__n", 1),
            ComparisonQuizItem("hawk", "h__k", 1),
            ComparisonQuizItem("lawn", "l__n", 1),
            ComparisonQuizItem("crawl", "cr__l", 1),
            ComparisonQuizItem("shawl", "sh__l", 1),
            ComparisonQuizItem("seesaw", "sees__", 1),
        ),
    ),

    PhonicsComparison(
        id = "c_k_ck", cardTitle = "c ⚡ k ⚡ ck", shortTitle = "c vs k vs ck",
        rule = "C likes a,o,u… K likes e,i… CK ends the word after a short vowel!",
        explanation = "All three make the same /k/ sound!\n• Use **c** before **a, o, u** (cat, cot, cup).\n• Use **k** before **e and i** (kite, key).\n• Right **after a short vowel at the end** → it is **ck** (du-ck).",
        example = "cat · kite · duck", group = ComparisonGroup.spelling,
        linkedLevelNumber = 5, linkedLevelLabel = "Level 5 · Spelling Rules",
        linkedRoute = RouteNavigation.ShortVowelRulesIntro.route,
        gradient = KidsGradient.aquaGreen, shape = KidsFloatingShape.bubbles,
        teams = listOf(
            ComparisonTeam("c", 0xFF2E7D32, "🐱", "+ a, o, u", markerAudio = "sound_c"),
            ComparisonTeam("k", 0xFF1565C0, "🪁", "+ e, i", markerAudio = "sound_k"),
            ComparisonTeam("ck", 0xFF7B1FA2, "🦆", "ends the word", markerAudio = "ck"),
        ),
        quiz = listOf(
            ComparisonQuizItem("cat", "_at", 0),
            ComparisonQuizItem("cap", "_ap", 0),
            ComparisonQuizItem("cup", "_up", 0),
            ComparisonQuizItem("cot", "_ot", 0),
            ComparisonQuizItem("can", "_an", 0),
            ComparisonQuizItem("car", "_ar", 0),
            ComparisonQuizItem("corn", "_orn", 0),
            ComparisonQuizItem("cub", "_ub", 0),
            ComparisonQuizItem("kite", "_ite", 1),
            ComparisonQuizItem("kit", "_it", 1),
            ComparisonQuizItem("key", "_ey", 1),
            ComparisonQuizItem("king", "_ing", 1),
            ComparisonQuizItem("kid", "_id", 1),
            ComparisonQuizItem("kiss", "_iss", 1),
            ComparisonQuizItem("kitten", "_itten", 1),
            ComparisonQuizItem("duck", "du__", 2),
            ComparisonQuizItem("sock", "so__", 2),
            ComparisonQuizItem("rock", "ro__", 2),
            ComparisonQuizItem("kick", "ki__", 2),
            ComparisonQuizItem("back", "ba__", 2),
            ComparisonQuizItem("neck", "ne__", 2),
            ComparisonQuizItem("black", "bla__", 2),
            ComparisonQuizItem("clock", "clo__", 2),
            ComparisonQuizItem("truck", "tru__", 2),
            ComparisonQuizItem("cut", "_ut", 0),
            ComparisonQuizItem("cake", "_ake", 0),
            ComparisonQuizItem("cold", "_old", 0),
            ComparisonQuizItem("card", "_ard", 0),
            ComparisonQuizItem("keep", "_eep", 1),
            ComparisonQuizItem("kind", "_ind", 1),
            ComparisonQuizItem("kettle", "_ettle", 1),
            ComparisonQuizItem("lock", "lo__", 2),
            ComparisonQuizItem("pick", "pi__", 2),
            ComparisonQuizItem("stick", "sti__", 2),
            ComparisonQuizItem("snack", "sna__", 2),
            ComparisonQuizItem("brick", "bri__", 2),
        ),
    ),

    PhonicsComparison(
        id = "ch_tch", cardTitle = "ch ⚡ tch", shortTitle = "ch vs tch",
        rule = "Right after a short vowel → TCH! Anywhere else → CH.",
        explanation = "Both spell the /ch/ sound.\n• Right **after a short vowel** at the end → add a silent t: **tch** (ca-tch, wa-tch).\n• Everywhere else → plain **ch** does the job (chip, chest).",
        example = "chip · catch", group = ComparisonGroup.spelling,
        linkedLevelNumber = 10, linkedLevelLabel = "Level 10 · Special Endings",
        linkedRoute = RouteNavigation.SpecialEndingsIntro.route,
        gradient = KidsGradient.mintLime, shape = KidsFloatingShape.curveLines,
        teams = listOf(
            ComparisonTeam("ch", 0xFF00897B, "🐤", "start / other spots", markerAudio = "ch"),
            ComparisonTeam("tch", 0xFFD32F2F, "⚾", "right after short vowel", markerAudio = "tch"),
        ),
        quiz = listOf(
            ComparisonQuizItem("chip", "__ip", 0),
            ComparisonQuizItem("chin", "__in", 0),
            ComparisonQuizItem("chat", "__at", 0),
            ComparisonQuizItem("chest", "__est", 0),
            ComparisonQuizItem("chop", "__op", 0),
            ComparisonQuizItem("chick", "__ick", 0),
            ComparisonQuizItem("cheese", "__eese", 0),
            ComparisonQuizItem("chair", "__air", 0),
            ComparisonQuizItem("chase", "__ase", 0),
            ComparisonQuizItem("catch", "ca___", 1),
            ComparisonQuizItem("watch", "wa___", 1),
            ComparisonQuizItem("match", "ma___", 1),
            ComparisonQuizItem("witch", "wi___", 1),
            ComparisonQuizItem("patch", "pa___", 1),
            ComparisonQuizItem("fetch", "fe___", 1),
            ComparisonQuizItem("scratch", "scra___", 1),
            ComparisonQuizItem("batch", "ba___", 1),
            ComparisonQuizItem("cheek", "__eek", 0),
            ComparisonQuizItem("chill", "__ill", 0),
            ComparisonQuizItem("lunch", "lun__", 0),
            ComparisonQuizItem("bench", "ben__", 0),
            ComparisonQuizItem("pitch", "pi___", 1),
            ComparisonQuizItem("switch", "swi___", 1),
            ComparisonQuizItem("itch", "i___", 1),
            ComparisonQuizItem("stitch", "sti___", 1),
            ComparisonQuizItem("stretch", "stre___", 1),
            ComparisonQuizItem("kitchen", "ki___en", 1),
            ComparisonQuizItem("hutch", "hu___", 1),
        ),
    ),

    PhonicsComparison(
        id = "ge_dge", cardTitle = "ge ⚡ dge", shortTitle = "ge vs dge",
        rule = "Right after a short vowel → DGE! After anything else → GE.",
        explanation = "Both spell the /j/ sound at the end of a word.\n• Right **after a short vowel** → add a silent d: **dge** (bri-dge, ba-dge).\n• After a **long vowel or another sound** → plain **ge** is enough (cage, page).",
        example = "cage · bridge", group = ComparisonGroup.spelling,
        linkedLevelNumber = 10, linkedLevelLabel = "Level 10 · Special Endings",
        linkedRoute = RouteNavigation.SpecialEndingsIntro.route,
        gradient = KidsGradient.lilacPink, shape = KidsFloatingShape.diamonds,
        teams = listOf(
            ComparisonTeam("ge", 0xFF1565C0, "🦅", "after long sounds", markerAudio = "ge"),
            ComparisonTeam("dge", 0xFF6D4C41, "🌉", "right after short vowel", markerAudio = "dge"),
        ),
        quiz = listOf(
            ComparisonQuizItem("cage", "ca__", 0),
            ComparisonQuizItem("page", "pa__", 0),
            ComparisonQuizItem("stage", "sta__", 0),
            ComparisonQuizItem("age", "a__", 0),
            ComparisonQuizItem("orange", "oran__", 0),
            ComparisonQuizItem("strange", "stran__", 0),
            ComparisonQuizItem("bridge", "bri___", 1),
            ComparisonQuizItem("fudge", "fu___", 1),
            ComparisonQuizItem("edge", "e___", 1),
            ComparisonQuizItem("badge", "ba___", 1),
            ComparisonQuizItem("judge", "ju___", 1),
            ComparisonQuizItem("hedge", "he___", 1),
            ComparisonQuizItem("dodge", "do___", 1),
            ComparisonQuizItem("wedge", "we___", 1),
            ComparisonQuizItem("huge", "hu__", 0),
            ComparisonQuizItem("large", "lar__", 0),
            ComparisonQuizItem("change", "chan__", 0),
            ComparisonQuizItem("village", "villa__", 0),
            ComparisonQuizItem("charge", "char__", 0),
            ComparisonQuizItem("sponge", "spon__", 0),
            ComparisonQuizItem("smudge", "smu___", 1),
            ComparisonQuizItem("lodge", "lo___", 1),
            ComparisonQuizItem("ledge", "le___", 1),
            ComparisonQuizItem("pledge", "ple___", 1),
        ),
    ),

    PhonicsComparison(
        id = "tion_sion", cardTitle = "tion ⚡ sion", shortTitle = "tion vs sion",
        rule = "-TION is the usual champion… -SION comes from S and D families!",
        explanation = "Both endings say /shun/.\n• Most words pick **-tion** (action, direction).\n• Words from a root ending in **s or d** — discuss→discussion, divide→division — pick **-sion**.",
        example = "action · vision", group = ComparisonGroup.spelling,
        linkedLevelNumber = 23, linkedLevelLabel = "Level 23 · Suffixes",
        linkedRoute = RouteNavigation.SuffixesIntro.route,
        gradient = KidsGradient.periwinkleBlue, shape = KidsFloatingShape.stars,
        teams = listOf(
            ComparisonTeam("tion", 0xFF2E7D32, "🏆", "the usual one", markerAudio = "tion"),
            ComparisonTeam("sion", 0xFFC62828, "🧩", "after s / d roots", markerAudio = "sion"),
        ),
        quiz = listOf(
            ComparisonQuizItem("action", "ac____", 0),
            ComparisonQuizItem("collection", "collec____", 0),
            ComparisonQuizItem("direction", "direc____", 0),
            ComparisonQuizItem("election", "elec____", 0),
            ComparisonQuizItem("vision", "vi____", 1),
            ComparisonQuizItem("mission", "mis____", 1),
            ComparisonQuizItem("confusion", "confu____", 1),
            ComparisonQuizItem("explosion", "explo____", 1),
            ComparisonQuizItem("discussion", "discus____", 1),
            ComparisonQuizItem("invasion", "inva____", 1),
            ComparisonQuizItem("nation", "na____", 0),
            ComparisonQuizItem("station", "sta____", 0),
            ComparisonQuizItem("motion", "mo____", 0),
            ComparisonQuizItem("lotion", "lo____", 0),
            ComparisonQuizItem("fiction", "fic____", 0),
            ComparisonQuizItem("mention", "men____", 0),
            ComparisonQuizItem("section", "sec____", 0),
            ComparisonQuizItem("vacation", "vaca____", 0),
            ComparisonQuizItem("invention", "inven____", 0),
            ComparisonQuizItem("addition", "addi____", 0),
            ComparisonQuizItem("television", "televi____", 1),
            ComparisonQuizItem("decision", "deci____", 1),
            ComparisonQuizItem("division", "divi____", 1),
            ComparisonQuizItem("conclusion", "conclu____", 1),
        ),
    ),

    PhonicsComparison(
        id = "oo_two", cardTitle = "oo 🌙⚡📖", shortTitle = "oo — moon or book?",
        rule = "OO usually howls a long “oooo” like the moon… a small book-family says a quick “u”!",
        explanation = "The same two letters make two sounds!\n• Most oo words stretch **long like a ghost** — moon, zoo, food.\n• A small family says a **short quick sound** — book, look, good.\nTip: **oo before k** almost always sounds like book!",
        example = "moon · book", group = ComparisonGroup.sound,
        linkedLevelNumber = 13, linkedLevelLabel = "Level 13 · Vowel Teams",
        linkedRoute = RouteNavigation.VowelTeamsIntro.route,
        gradient = KidsGradient.indigoPurple, shape = KidsFloatingShape.musicNotes,
        teams = listOf(
            ComparisonTeam("oo", 0xFF5E35B1, "🌙", "long “oooo”", markerAudio = "oo"),
            ComparisonTeam("oo", 0xFFE65100, "📖", "quick “u”", markerAudio = "oo2"),
        ),
        quiz = listOf(
            ComparisonQuizItem("moon", "moon", 0),
            ComparisonQuizItem("food", "food", 0),
            ComparisonQuizItem("zoo", "zoo", 0),
            ComparisonQuizItem("pool", "pool", 0),
            ComparisonQuizItem("room", "room", 0),
            ComparisonQuizItem("spoon", "spoon", 0),
            ComparisonQuizItem("school", "school", 0),
            ComparisonQuizItem("tooth", "tooth", 0),
            ComparisonQuizItem("book", "book", 1),
            ComparisonQuizItem("look", "look", 1),
            ComparisonQuizItem("good", "good", 1),
            ComparisonQuizItem("foot", "foot", 1),
            ComparisonQuizItem("cook", "cook", 1),
            ComparisonQuizItem("wood", "wood", 1),
            ComparisonQuizItem("hook", "hook", 1),
            ComparisonQuizItem("took", "took", 1),
            ComparisonQuizItem("roof", "roof", 0),
            ComparisonQuizItem("cool", "cool", 0),
            ComparisonQuizItem("boot", "boot", 0),
            ComparisonQuizItem("broom", "broom", 0),
            ComparisonQuizItem("scoop", "scoop", 0),
            ComparisonQuizItem("noon", "noon", 0),
            ComparisonQuizItem("igloo", "igloo", 0),
            ComparisonQuizItem("balloon", "balloon", 0),
            ComparisonQuizItem("stood", "stood", 1),
            ComparisonQuizItem("shook", "shook", 1),
            ComparisonQuizItem("wool", "wool", 1),
            ComparisonQuizItem("brook", "brook", 1),
        ),
    ),

    PhonicsComparison(
        id = "ea_two", cardTitle = "ea 🌿⚡🍞", shortTitle = "ea — read or bread?",
        rule = "EA usually says /ē/ like read… the bread-family says short /e/!",
        explanation = "Most ea words say the **long-E** sound — read, team, beach.\nBut a little bread-family says **short /e/** instead — bread, head, ready.\nThere is no rule for these rebels; meet them often and you will remember them!",
        example = "read · bread", group = ComparisonGroup.sound,
        linkedLevelNumber = 13, linkedLevelLabel = "Level 13 · Vowel Teams",
        linkedRoute = RouteNavigation.VowelTeamsIntro.route,
        gradient = KidsGradient.meadowGreen, shape = KidsFloatingShape.leaves,
        teams = listOf(
            ComparisonTeam("ea", 0xFF00897B, "🌿", "long /ē/", markerAudio = "ea"),
            ComparisonTeam("ea", 0xFF6D4C41, "🍞", "short /e/", markerAudio = "sound_e"),
        ),
        quiz = listOf(
            ComparisonQuizItem("read", "read", 0),
            ComparisonQuizItem("team", "team", 0),
            ComparisonQuizItem("beach", "beach", 0),
            ComparisonQuizItem("dream", "dream", 0),
            ComparisonQuizItem("eat", "eat", 0),
            ComparisonQuizItem("clean", "clean", 0),
            ComparisonQuizItem("bread", "bread", 1),
            ComparisonQuizItem("head", "head", 1),
            ComparisonQuizItem("ready", "ready", 1),
            ComparisonQuizItem("heavy", "heavy", 1),
            ComparisonQuizItem("spread", "spread", 1),
            ComparisonQuizItem("thread", "thread", 1),
            ComparisonQuizItem("sea", "sea", 0),
            ComparisonQuizItem("tea", "tea", 0),
            ComparisonQuizItem("leaf", "leaf", 0),
            ComparisonQuizItem("meat", "meat", 0),
            ComparisonQuizItem("peach", "peach", 0),
            ComparisonQuizItem("seat", "seat", 0),
            ComparisonQuizItem("cream", "cream", 0),
            ComparisonQuizItem("steam", "steam", 0),
            ComparisonQuizItem("feather", "feather", 1),
            ComparisonQuizItem("weather", "weather", 1),
            ComparisonQuizItem("sweater", "sweater", 1),
            ComparisonQuizItem("breakfast", "breakfast", 1),
            ComparisonQuizItem("instead", "instead", 1),
        ),
    ),

    PhonicsComparison(
        id = "ow_two", cardTitle = "ow ❄️⚡🐮", shortTitle = "ow — snow or cow?",
        rule = "OW says /ō/ in snow… and /ow!/ in cow!",
        explanation = "The same ow can sing two songs.\n• Sometimes the **calm long-O** of snow, grow and show.\n• Sometimes the **loud /ow!/** of cow, how and now — like when you stub your toe.\nSay the word **both ways** and pick the one that sounds real!",
        example = "snow · cow", group = ComparisonGroup.sound,
        linkedLevelNumber = 13, linkedLevelLabel = "Level 13 · Vowel Teams",
        linkedRoute = RouteNavigation.VowelTeamsIntro.route,
        gradient = KidsGradient.softBlue, shape = KidsFloatingShape.sparkles,
        teams = listOf(
            ComparisonTeam("ow", 0xFF0277BD, "❄️", "long /ō/", markerAudio = "ow"),
            ComparisonTeam("ow", 0xFFBF360C, "🐮", "loud /ow!/", markerAudio = "ow2"),
        ),
        quiz = listOf(
            ComparisonQuizItem("snow", "snow", 0),
            ComparisonQuizItem("grow", "grow", 0),
            ComparisonQuizItem("blow", "blow", 0),
            ComparisonQuizItem("show", "show", 0),
            ComparisonQuizItem("slow", "slow", 0),
            ComparisonQuizItem("glow", "glow", 0),
            ComparisonQuizItem("flow", "flow", 0),
            ComparisonQuizItem("cow", "cow", 1),
            ComparisonQuizItem("how", "how", 1),
            ComparisonQuizItem("now", "now", 1),
            ComparisonQuizItem("town", "town", 1),
            ComparisonQuizItem("down", "down", 1),
            ComparisonQuizItem("brown", "brown", 1),
            ComparisonQuizItem("crown", "crown", 1),
            ComparisonQuizItem("clown", "clown", 1),
            ComparisonQuizItem("row", "row", 0),
            ComparisonQuizItem("low", "low", 0),
            ComparisonQuizItem("window", "window", 0),
            ComparisonQuizItem("yellow", "yellow", 0),
            ComparisonQuizItem("pillow", "pillow", 0),
            ComparisonQuizItem("rainbow", "rainbow", 0),
            ComparisonQuizItem("elbow", "elbow", 0),
            ComparisonQuizItem("owl", "owl", 1),
            ComparisonQuizItem("frown", "frown", 1),
            ComparisonQuizItem("gown", "gown", 1),
            ComparisonQuizItem("wow", "wow", 1),
        ),
    ),

    PhonicsComparison(
        id = "th_two", cardTitle = "th 👄⚡🐝", shortTitle = "th — thin or that?",
        rule = "Helper words BUZZ 🐝 — thing words blow soft air 👄!",
        explanation = "Put your **hand on your throat** — here's WHEN each th shows up:\n• **Buzzy 🐝** — little **helper words**: the, this, that, they, them, then, there… and **family words**: mother, father, brother.\n• **Soft air 👄** — most **thing words**: think, three, thumb, thick… and th at the **end**: bath, math, teeth.\nNot a helper word? Try **soft air** first!",
        example = "thin · that", group = ComparisonGroup.sound,
        linkedLevelNumber = 9, linkedLevelLabel = "Level 9 · Digraphs",
        linkedRoute = RouteNavigation.DigraphsIntro.route,
        gradient = KidsGradient.tealCyan, shape = KidsFloatingShape.speechBubbles,
        teams = listOf(
            ComparisonTeam("th", 0xFF00897B, "👄", "thing words + ends", markerAudio = "th"),
            ComparisonTeam("th", 0xFFF9A825, "🐝", "helper + family words", markerAudio = "th2"),
        ),
        quiz = listOf(
            ComparisonQuizItem("thin", "thin", 0),
            ComparisonQuizItem("three", "three", 0),
            ComparisonQuizItem("thumb", "thumb", 0),
            ComparisonQuizItem("bath", "bath", 0),
            ComparisonQuizItem("think", "think", 0),
            ComparisonQuizItem("thick", "thick", 0),
            ComparisonQuizItem("throw", "throw", 0),
            ComparisonQuizItem("thank", "thank", 0),
            ComparisonQuizItem("that", "that", 1),
            ComparisonQuizItem("this", "this", 1),
            ComparisonQuizItem("them", "them", 1),
            ComparisonQuizItem("they", "they", 1),
            ComparisonQuizItem("the", "the", 1),
            ComparisonQuizItem("there", "there", 1),
            ComparisonQuizItem("third", "third", 0),
            ComparisonQuizItem("teeth", "teeth", 0),
            ComparisonQuizItem("math", "math", 0),
            ComparisonQuizItem("moth", "moth", 0),
            ComparisonQuizItem("path", "path", 0),
            ComparisonQuizItem("then", "then", 1),
            ComparisonQuizItem("mother", "mother", 1),
            ComparisonQuizItem("father", "father", 1),
            ComparisonQuizItem("brother", "brother", 1),
            ComparisonQuizItem("together", "together", 1),
        ),
    ),

    PhonicsComparison(
        id = "ed_two", cardTitle = "ed 🥾⚡🔔⚡🌱", shortTitle = "ed — /t/, /d/ or /id/?",
        rule = "After quiet sounds ED whispers /t/… after noisy sounds /d/… after t and d it sings /id/!",
        explanation = "The past-tense ed has three voices!\n• After **quiet sounds** like p, k, s → it whispers **/t/** (jump-t, walk-t).\n• After **noisy (voiced) sounds** → it says **/d/** (play-d, clean-d).\n• Right **after t or d** → it needs an **extra beat /id/** (plant-id, need-id).\nSay the word and **listen to the very last sound**!",
        example = "jumped · played · planted", group = ComparisonGroup.sound,
        linkedLevelNumber = 21, linkedLevelLabel = "Level 21 · Word Endings",
        linkedRoute = RouteNavigation.WordEndingsIntro.route,
        gradient = KidsGradient.peachCoral, shape = KidsFloatingShape.stars,
        teams = listOf(
            ComparisonTeam("/t/", 0xFF455A64, "🥾", "whisper", markerAudio = "sound_t", highlight = "ed"),
            ComparisonTeam("/d/", 0xFF1565C0, "🔔", "voiced", markerAudio = "sound_d", highlight = "ed"),
            ComparisonTeam("/id/", 0xFF2E7D32, "🌱", "extra beat", markerAudio = "id", highlight = "ed"),
        ),
        quiz = listOf(
            ComparisonQuizItem("jumped", "jumped", 0),
            ComparisonQuizItem("baked", "baked", 0),
            ComparisonQuizItem("walked", "walked", 0),
            ComparisonQuizItem("talked", "talked", 0),
            ComparisonQuizItem("cooked", "cooked", 0),
            ComparisonQuizItem("hoped", "hoped", 0),
            ComparisonQuizItem("stopped", "stopped", 0),
            ComparisonQuizItem("clapped", "clapped", 0),
            ComparisonQuizItem("played", "played", 1),
            ComparisonQuizItem("cleaned", "cleaned", 1),
            ComparisonQuizItem("loved", "loved", 1),
            ComparisonQuizItem("rained", "rained", 1),
            ComparisonQuizItem("smiled", "smiled", 1),
            ComparisonQuizItem("moved", "moved", 1),
            ComparisonQuizItem("danced", "danced", 0),
            ComparisonQuizItem("asked", "asked", 0),
            ComparisonQuizItem("liked", "liked", 0),
            ComparisonQuizItem("picked", "picked", 0),
            ComparisonQuizItem("fixed", "fixed", 0),
            ComparisonQuizItem("mixed", "mixed", 0),
            ComparisonQuizItem("washed", "washed", 0),
            ComparisonQuizItem("helped", "helped", 0),
            ComparisonQuizItem("looked", "looked", 0),
            ComparisonQuizItem("kicked", "kicked", 0),
            ComparisonQuizItem("called", "called", 1),
            ComparisonQuizItem("opened", "opened", 1),
            ComparisonQuizItem("saved", "saved", 1),
            ComparisonQuizItem("hugged", "hugged", 1),
            ComparisonQuizItem("stayed", "stayed", 1),
            ComparisonQuizItem("climbed", "climbed", 1),
            ComparisonQuizItem("yelled", "yelled", 1),
            ComparisonQuizItem("waved", "waved", 1),
            ComparisonQuizItem("planted", "planted", 2),
            ComparisonQuizItem("wanted", "wanted", 2),
            ComparisonQuizItem("painted", "painted", 2),
            ComparisonQuizItem("needed", "needed", 2),
            ComparisonQuizItem("ended", "ended", 2),
            ComparisonQuizItem("folded", "folded", 2),
            ComparisonQuizItem("landed", "landed", 2),
            ComparisonQuizItem("shouted", "shouted", 2),
            ComparisonQuizItem("counted", "counted", 2),
        ),
    ),

    PhonicsComparison(
        id = "c_two", cardTitle = "c 🐱⚡🏙️", shortTitle = "c — cat or city?",
        rule = "Hard /k/ like CAT… soft /s/ before e, i, y like CITY!",
        explanation = "The letter c has two voices.\n• Before **a, o, u** → **hard like /k/** (cat, cup).\n• Before **e, i or y** → c turns **soft and hisses /s/** (city, ice, mice).\nCheck the letter **after** the c!",
        example = "cat · city", group = ComparisonGroup.sound,
        linkedLevelNumber = 19, linkedLevelLabel = "Level 19 · Soft C & Soft G",
        linkedRoute = RouteNavigation.SoftCSoftGIntro.route,
        gradient = KidsGradient.rosePink, shape = KidsFloatingShape.hearts,
        teams = listOf(
            ComparisonTeam("c", 0xFF2E7D32, "🐱", "hard /k/", markerAudio = "sound_c"),
            ComparisonTeam("c", 0xFF0277BD, "🏙️", "soft /s/ + e,i,y", markerAudio = "sound_s"),
        ),
        quiz = listOf(
            ComparisonQuizItem("cat", "cat", 0),
            ComparisonQuizItem("cap", "cap", 0),
            ComparisonQuizItem("cup", "cup", 0),
            ComparisonQuizItem("can", "can", 0),
            ComparisonQuizItem("car", "car", 0),
            ComparisonQuizItem("corn", "corn", 0),
            ComparisonQuizItem("cut", "cut", 0),
            ComparisonQuizItem("cub", "cub", 0),
            ComparisonQuizItem("city", "city", 1),
            ComparisonQuizItem("ice", "ice", 1),
            ComparisonQuizItem("mice", "mice", 1),
            ComparisonQuizItem("face", "face", 1),
            ComparisonQuizItem("circle", "circle", 1),
            ComparisonQuizItem("cell", "cell", 1),
            ComparisonQuizItem("dance", "dance", 1),
            ComparisonQuizItem("juice", "juice", 1),
            ComparisonQuizItem("cake", "cake", 0),
            ComparisonQuizItem("cold", "cold", 0),
            ComparisonQuizItem("cost", "cost", 0),
            ComparisonQuizItem("card", "card", 0),
            ComparisonQuizItem("rice", "rice", 1),
            ComparisonQuizItem("race", "race", 1),
            ComparisonQuizItem("pencil", "pencil", 1),
            ComparisonQuizItem("fence", "fence", 1),
            ComparisonQuizItem("cent", "cent", 1),
        ),
    ),

    PhonicsComparison(
        id = "g_two", cardTitle = "g 🐐⚡💎", shortTitle = "g — goat or gem?",
        rule = "Hard /g/ like GOAT… soft /j/ before e, i, y like GEM!",
        explanation = "Just like c, the letter g has two voices.\n• Before **a, o, u** → **hard** (goat, game, gum).\n• Before **e, i or y** → usually **soft into /j/** (gem, giraffe, gym).\nPeek at the letter **after** the g!",
        example = "goat · gem", group = ComparisonGroup.sound,
        linkedLevelNumber = 19, linkedLevelLabel = "Level 19 · Soft C & Soft G",
        linkedRoute = RouteNavigation.SoftCSoftGIntro.route,
        gradient = KidsGradient.purpleBlue, shape = KidsFloatingShape.diamonds,
        teams = listOf(
            ComparisonTeam("g", 0xFF6D4C41, "🐐", "hard /g/", markerAudio = "sound_g"),
            ComparisonTeam("g", 0xFF7B1FA2, "💎", "soft /j/ + e,i,y", markerAudio = "sound_j"),
        ),
        quiz = listOf(
            ComparisonQuizItem("goat", "goat", 0),
            ComparisonQuizItem("gum", "gum", 0),
            ComparisonQuizItem("game", "game", 0),
            ComparisonQuizItem("gift", "gift", 0),
            ComparisonQuizItem("girl", "girl", 0),
            ComparisonQuizItem("go", "go", 0),
            ComparisonQuizItem("gold", "gold", 0),
            ComparisonQuizItem("gas", "gas", 0),
            ComparisonQuizItem("gem", "gem", 1),
            ComparisonQuizItem("giraffe", "giraffe", 1),
            ComparisonQuizItem("gym", "gym", 1),
            ComparisonQuizItem("gentle", "gentle", 1),
            ComparisonQuizItem("giant", "giant", 1),
            ComparisonQuizItem("ginger", "ginger", 1),
            ComparisonQuizItem("germ", "germ", 1),
            ComparisonQuizItem("garden", "garden", 0),
            ComparisonQuizItem("gate", "gate", 0),
            ComparisonQuizItem("goose", "goose", 0),
            ComparisonQuizItem("magic", "magic", 1),
            ComparisonQuizItem("energy", "energy", 1),
            ComparisonQuizItem("cabbage", "cabbage", 1),
        ),
    ),

)

fun phonicsComparison(id: String): PhonicsComparison? =
    phonicsComparisons.firstOrNull { it.id == id }

/** Fun-fact card shown under the Compare & Choose grid. */
val phonicsFunFacts = listOf(
    "English words never end in i — that's why it's my and fly!",
    "English words never end in v — that's why have, give and love wear a silent e!",
    "English words never end in j — that's why we write cage and badge!",
    "Q never goes anywhere without its best friend U — quiz, queen, quick!",
    "Every word needs a vowel — when there isn't one, Y does the job: gym, fly, my!",
    "E is the most used letter in English — and it's often totally silent: cake, bike, home!",
    "Right after a short vowel, f, l, s and z double up — off, bell, miss, buzz!",
    "The word “the” is the most used word in all of English!",
)
